### ISSUE TITLE
Issue with capitalization in require('dateFormat')

### ISSUE THREAD

**Issue by bkozlik** [coyotebringsfire/mocha-mongo-reporter#2]
Hello,

Thanks for sharing this project. 

When trying to run this on Centos I got an exception stating that the dateformat dependency was failing. Turns out that you have a small capitalization typo in there that causes this error on linux (or perhaps a recent version of node introduced module name case sensitivity):

https://github.com/coyotebringsfire/mocha-mongo-reporter/blob/master/mocha-mongo-reporter.js

on line 3:
dateFormat  = require('dateFormat'), now;

should be

dateFormat  = require('dateformat'), now;

Thanks! 

Regards,
Blaze Kozlik

**Comment by coyotebringsfire** [comment]
thanks, I have no idea how that ever worked. I fixed the typo in 8e99c88 version 0.2.1
